// <auto-generated />
using System;
using DAIF2020.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAIF2020.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200105024052_AcvitvitiesAdded")]
    partial class AcvitvitiesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAIF2020.Models.DataModels.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArenaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArenaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ArenaStatusId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArenaStatusId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Arena");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArenaId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClubName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClubNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClubStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("ClubStatusId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("District");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArenaId")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamScore")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId1")
                        .HasColumnType("int");

                    b.Property<int?>("GameCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("GameTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamScore")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId1")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId2")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId3")
                        .HasColumnType("int");

                    b.Property<string>("TSMNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("ClubId");

                    b.HasIndex("ClubId1");

                    b.HasIndex("GameCategoryId");

                    b.HasIndex("GameStatusId");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId1");

                    b.HasIndex("PersonId2");

                    b.HasIndex("PersonId3");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ssn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwishNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("PersonRoleId");

                    b.HasIndex("PersonStatusId");

                    b.HasIndex("PersonTypeId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.PoolGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArenaId")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PoolGameDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PoolGameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZoneGameId")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneGameId1")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneGameId2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("ClubId");

                    b.HasIndex("ZoneGameId");

                    b.HasIndex("ZoneGameId1");

                    b.HasIndex("ZoneGameId2");

                    b.ToTable("PoolGame");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("SeriesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeriesStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SeriesStatusId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArenaId")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamRosterId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("ClubId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("TeamRosterId");

                    b.HasIndex("TeamStatusId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.TeamRoster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId1")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId2")
                        .HasColumnType("int");

                    b.Property<string>("TeamRosterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId1");

                    b.HasIndex("PersonId2");

                    b.ToTable("TeamRoster");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Tornament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("GameId1")
                        .HasColumnType("int");

                    b.Property<int?>("GameId10")
                        .HasColumnType("int");

                    b.Property<int?>("GameId11")
                        .HasColumnType("int");

                    b.Property<int?>("GameId12")
                        .HasColumnType("int");

                    b.Property<int?>("GameId13")
                        .HasColumnType("int");

                    b.Property<int?>("GameId14")
                        .HasColumnType("int");

                    b.Property<int?>("GameId2")
                        .HasColumnType("int");

                    b.Property<int?>("GameId3")
                        .HasColumnType("int");

                    b.Property<int?>("GameId4")
                        .HasColumnType("int");

                    b.Property<int?>("GameId5")
                        .HasColumnType("int");

                    b.Property<int?>("GameId6")
                        .HasColumnType("int");

                    b.Property<int?>("GameId7")
                        .HasColumnType("int");

                    b.Property<int?>("GameId8")
                        .HasColumnType("int");

                    b.Property<int?>("GameId9")
                        .HasColumnType("int");

                    b.Property<DateTime>("TournamentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TournamentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TournamentTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId1");

                    b.HasIndex("GameId10");

                    b.HasIndex("GameId11");

                    b.HasIndex("GameId12");

                    b.HasIndex("GameId13");

                    b.HasIndex("GameId14");

                    b.HasIndex("GameId2");

                    b.HasIndex("GameId3");

                    b.HasIndex("GameId4");

                    b.HasIndex("GameId5");

                    b.HasIndex("GameId6");

                    b.HasIndex("GameId7");

                    b.HasIndex("GameId8");

                    b.HasIndex("GameId9");

                    b.HasIndex("TournamentTypeId");

                    b.ToTable("Tornament");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.ZoneGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArenaId")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId1")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId2")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId3")
                        .HasColumnType("int");

                    b.Property<int?>("GameCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("GameStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("GameTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId1")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId2")
                        .HasColumnType("int");

                    b.Property<string>("TSMNumberZone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TSMNumberZone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ZoneGameDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZoneGameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("ClubId");

                    b.HasIndex("ClubId1");

                    b.HasIndex("ClubId2");

                    b.HasIndex("ClubId3");

                    b.HasIndex("GameCategoryId");

                    b.HasIndex("GameStatusId");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId1");

                    b.HasIndex("PersonId2");

                    b.HasIndex("ZoneId");

                    b.HasIndex("ZoneId1");

                    b.ToTable("ZoneGame");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.ActivityStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityStatus");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.ArenaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArenaStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArenaStatus");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.ClubStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClubStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClubStatus");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameCategory");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.GameStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameStatus");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameType");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.PersonRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersonRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonRole");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.PersonStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersonStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonStatus");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.PersonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersonTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonType");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.ReceiptCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReceiptCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReceiptCategory");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.ReceiptStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReceiptStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReceiptStatus");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.ReceiptType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReceiptTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReceiptType");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.SeriesStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SeriesStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SeriesStatus");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.TeamStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeamStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamStatus");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.TournamentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TournamentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TournamentType");
                });

            modelBuilder.Entity("DAIF2020.Models.SettingModels.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ZoneName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("DAIF2020.Planner.Models.DataModels.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActivityStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityStatusId");

                    b.HasIndex("GameId");

                    b.HasIndex("PersonId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("DAIF2020.TSM.Models.DataModels.TSMGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Arena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GameDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GameNumber")
                        .HasColumnType("int");

                    b.Property<string>("HD1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HD2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LD1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LD2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Round")
                        .HasColumnType("int");

                    b.Property<string>("Series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TSMGameStatusId")
                        .HasColumnType("int");

                    b.Property<string>("WeekDay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TSMGameStatusId");

                    b.ToTable("TSMGame");
                });

            modelBuilder.Entity("DAIF2020.TSM.Models.DataModels.TSMGameStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TSMGameStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TSMGameStatus");
                });

            modelBuilder.Entity("DAIF2020.TheLab.Models.DataModels.PoolGameReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountPaidUDZ1")
                        .HasColumnType("int");

                    b.Property<int>("AmountPaidUDZ2")
                        .HasColumnType("int");

                    b.Property<int>("DUZ1LateGameKost")
                        .HasColumnType("int");

                    b.Property<int?>("PoolGameId")
                        .HasColumnType("int");

                    b.Property<int>("PoolGameTotalKost")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmountPaid")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmountToPay")
                        .HasColumnType("int");

                    b.Property<int>("UDZ1Alowens")
                        .HasColumnType("int");

                    b.Property<int>("UDZ1Fee")
                        .HasColumnType("int");

                    b.Property<int>("UDZ1Other")
                        .HasColumnType("int");

                    b.Property<int>("UDZ1TotalFee")
                        .HasColumnType("int");

                    b.Property<int>("UDZ1TravelKost")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2Alowens")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2Fee")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2LateGameKost")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2Other")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2TotalFee")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2TravelKost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoolGameId");

                    b.HasIndex("ReceiptCategoryId");

                    b.HasIndex("ReceiptStatusId");

                    b.HasIndex("ReceiptTypeId");

                    b.ToTable("PoolGameReceipt");
                });

            modelBuilder.Entity("DAIF2020.TheLab.Models.DataModels.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountPaidHD1")
                        .HasColumnType("int");

                    b.Property<int>("AmountPaidHD2")
                        .HasColumnType("int");

                    b.Property<int>("AmountPaidLD1")
                        .HasColumnType("int");

                    b.Property<int>("AmountPaidLD2")
                        .HasColumnType("int");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GameTotalKost")
                        .HasColumnType("int");

                    b.Property<int>("HD1Alowens")
                        .HasColumnType("int");

                    b.Property<int>("HD1Fee")
                        .HasColumnType("int");

                    b.Property<int>("HD1LateGameKost")
                        .HasColumnType("int");

                    b.Property<int>("HD1Other")
                        .HasColumnType("int");

                    b.Property<int>("HD1TotalFee")
                        .HasColumnType("int");

                    b.Property<int>("HD1TravelKost")
                        .HasColumnType("int");

                    b.Property<int>("HD2Alowens")
                        .HasColumnType("int");

                    b.Property<int>("HD2Fee")
                        .HasColumnType("int");

                    b.Property<int>("HD2LateGameKost")
                        .HasColumnType("int");

                    b.Property<int>("HD2Other")
                        .HasColumnType("int");

                    b.Property<int>("HD2TotalFee")
                        .HasColumnType("int");

                    b.Property<int>("HD2TravelKost")
                        .HasColumnType("int");

                    b.Property<int>("LD1Alowens")
                        .HasColumnType("int");

                    b.Property<int>("LD1Fee")
                        .HasColumnType("int");

                    b.Property<int>("LD1LateGameKost")
                        .HasColumnType("int");

                    b.Property<int>("LD1Other")
                        .HasColumnType("int");

                    b.Property<int>("LD1TotalFee")
                        .HasColumnType("int");

                    b.Property<int>("LD1TravelKost")
                        .HasColumnType("int");

                    b.Property<int>("LD2Alowens")
                        .HasColumnType("int");

                    b.Property<int>("LD2Fee")
                        .HasColumnType("int");

                    b.Property<int>("LD2LateGameKost")
                        .HasColumnType("int");

                    b.Property<int>("LD2Other")
                        .HasColumnType("int");

                    b.Property<int>("LD2TotalFee")
                        .HasColumnType("int");

                    b.Property<int>("LD2TravelKost")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmountPaid")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmountToPay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ReceiptCategoryId");

                    b.HasIndex("ReceiptStatusId");

                    b.HasIndex("ReceiptTypeId");

                    b.ToTable("Receipt");
                });

            modelBuilder.Entity("DAIF2020.TheLab.Models.DataModels.WeeklyReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ReceiptStatusId");

                    b.ToTable("WeeklyReciept");
                });

            modelBuilder.Entity("DAIF2020.TheLab.Models.DataModels.ZoneGameReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountPaidUDZ1")
                        .HasColumnType("int");

                    b.Property<int>("AmountPaidUDZ2")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmountPaid")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmountToPay")
                        .HasColumnType("int");

                    b.Property<int>("UDZ1Alowens")
                        .HasColumnType("int");

                    b.Property<int>("UDZ1Fee")
                        .HasColumnType("int");

                    b.Property<int>("UDZ1LateGameKost")
                        .HasColumnType("int");

                    b.Property<int>("UDZ1Other")
                        .HasColumnType("int");

                    b.Property<int>("UDZ1TotalFee")
                        .HasColumnType("int");

                    b.Property<int>("UDZ1TravelKost")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2Alowens")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2Fee")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2LateGameKost")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2Other")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2TotalFee")
                        .HasColumnType("int");

                    b.Property<int>("UDZ2TravelKost")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneGameId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneGameTotalKost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptCategoryId");

                    b.HasIndex("ReceiptStatusId");

                    b.HasIndex("ReceiptTypeId");

                    b.HasIndex("ZoneGameId");

                    b.ToTable("ZoneGameReceipt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Arena", b =>
                {
                    b.HasOne("DAIF2020.Models.SettingModels.ArenaStatus", "ArenaStatus")
                        .WithMany()
                        .HasForeignKey("ArenaStatusId");

                    b.HasOne("DAIF2020.Models.DataModels.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Club", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.Arena", "Arena")
                        .WithMany()
                        .HasForeignKey("ArenaId");

                    b.HasOne("DAIF2020.Models.SettingModels.ClubStatus", "ClubStatus")
                        .WithMany()
                        .HasForeignKey("ClubStatusId");

                    b.HasOne("DAIF2020.Models.DataModels.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Game", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.Arena", "Arena")
                        .WithMany()
                        .HasForeignKey("ArenaId");

                    b.HasOne("DAIF2020.Models.DataModels.Club", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("ClubId");

                    b.HasOne("DAIF2020.Models.DataModels.Club", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("ClubId1");

                    b.HasOne("DAIF2020.Models.SettingModels.GameCategory", "GameCategory")
                        .WithMany()
                        .HasForeignKey("GameCategoryId");

                    b.HasOne("DAIF2020.Models.SettingModels.GameStatus", "GameStatus")
                        .WithMany()
                        .HasForeignKey("GameStatusId");

                    b.HasOne("DAIF2020.Models.SettingModels.GameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeId");

                    b.HasOne("DAIF2020.Models.DataModels.Person", "HD1")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("DAIF2020.Models.DataModels.Person", "HD2")
                        .WithMany()
                        .HasForeignKey("PersonId1");

                    b.HasOne("DAIF2020.Models.DataModels.Person", "LD1")
                        .WithMany()
                        .HasForeignKey("PersonId2");

                    b.HasOne("DAIF2020.Models.DataModels.Person", "LD2")
                        .WithMany()
                        .HasForeignKey("PersonId3");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Person", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId");

                    b.HasOne("DAIF2020.Models.DataModels.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("DAIF2020.Models.SettingModels.PersonRole", "PersonRole")
                        .WithMany()
                        .HasForeignKey("PersonRoleId");

                    b.HasOne("DAIF2020.Models.SettingModels.PersonStatus", "PersonStatus")
                        .WithMany()
                        .HasForeignKey("PersonStatusId");

                    b.HasOne("DAIF2020.Models.SettingModels.PersonType", "PersonType")
                        .WithMany()
                        .HasForeignKey("PersonTypeId");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.PoolGame", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.Arena", "Arena")
                        .WithMany()
                        .HasForeignKey("ArenaId");

                    b.HasOne("DAIF2020.Models.DataModels.Club", "HostingTeam")
                        .WithMany()
                        .HasForeignKey("ClubId");

                    b.HasOne("DAIF2020.Models.DataModels.ZoneGame", "ZoneGame1")
                        .WithMany()
                        .HasForeignKey("ZoneGameId");

                    b.HasOne("DAIF2020.Models.DataModels.ZoneGame", "ZoneGame2")
                        .WithMany()
                        .HasForeignKey("ZoneGameId1");

                    b.HasOne("DAIF2020.Models.DataModels.ZoneGame", "ZoneGame3")
                        .WithMany()
                        .HasForeignKey("ZoneGameId2");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Series", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("DAIF2020.Models.DataModels.Person", "Admin")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("DAIF2020.Models.SettingModels.SeriesStatus", "SeriesStatus")
                        .WithMany()
                        .HasForeignKey("SeriesStatusId");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Team", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.Arena", "Arena")
                        .WithMany()
                        .HasForeignKey("ArenaId");

                    b.HasOne("DAIF2020.Models.DataModels.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId");

                    b.HasOne("DAIF2020.Models.DataModels.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("DAIF2020.Models.DataModels.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId");

                    b.HasOne("DAIF2020.Models.DataModels.TeamRoster", "TeamRoster")
                        .WithMany()
                        .HasForeignKey("TeamRosterId");

                    b.HasOne("DAIF2020.Models.SettingModels.TeamStatus", "TeamStatus")
                        .WithMany()
                        .HasForeignKey("TeamStatusId");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.TeamRoster", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.Person", "GM")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("DAIF2020.Models.DataModels.Person", "HeadCoach")
                        .WithMany()
                        .HasForeignKey("PersonId1");

                    b.HasOne("DAIF2020.Models.DataModels.Person", "AssCoach")
                        .WithMany()
                        .HasForeignKey("PersonId2");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.Tornament", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game1")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game2")
                        .WithMany()
                        .HasForeignKey("GameId1");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game11")
                        .WithMany()
                        .HasForeignKey("GameId10");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game12")
                        .WithMany()
                        .HasForeignKey("GameId11");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game13")
                        .WithMany()
                        .HasForeignKey("GameId12");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game14")
                        .WithMany()
                        .HasForeignKey("GameId13");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game15")
                        .WithMany()
                        .HasForeignKey("GameId14");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game3")
                        .WithMany()
                        .HasForeignKey("GameId2");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game4")
                        .WithMany()
                        .HasForeignKey("GameId3");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game5")
                        .WithMany()
                        .HasForeignKey("GameId4");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game6")
                        .WithMany()
                        .HasForeignKey("GameId5");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game7")
                        .WithMany()
                        .HasForeignKey("GameId6");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game8")
                        .WithMany()
                        .HasForeignKey("GameId7");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game9")
                        .WithMany()
                        .HasForeignKey("GameId8");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game10")
                        .WithMany()
                        .HasForeignKey("GameId9");

                    b.HasOne("DAIF2020.Models.SettingModels.TournamentType", "TournamentType")
                        .WithMany()
                        .HasForeignKey("TournamentTypeId");
                });

            modelBuilder.Entity("DAIF2020.Models.DataModels.ZoneGame", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.Arena", "Arena")
                        .WithMany()
                        .HasForeignKey("ArenaId");

                    b.HasOne("DAIF2020.Models.DataModels.Club", "HomeTeam1")
                        .WithMany()
                        .HasForeignKey("ClubId");

                    b.HasOne("DAIF2020.Models.DataModels.Club", "AwayTeam1")
                        .WithMany()
                        .HasForeignKey("ClubId1");

                    b.HasOne("DAIF2020.Models.DataModels.Club", "HomeTeam2")
                        .WithMany()
                        .HasForeignKey("ClubId2");

                    b.HasOne("DAIF2020.Models.DataModels.Club", "AwayTeam2")
                        .WithMany()
                        .HasForeignKey("ClubId3");

                    b.HasOne("DAIF2020.Models.SettingModels.GameCategory", "GameCategory")
                        .WithMany()
                        .HasForeignKey("GameCategoryId");

                    b.HasOne("DAIF2020.Models.SettingModels.GameStatus", "GameStatus")
                        .WithMany()
                        .HasForeignKey("GameStatusId");

                    b.HasOne("DAIF2020.Models.SettingModels.GameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeId");

                    b.HasOne("DAIF2020.Models.DataModels.Person", "UDZ1")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("DAIF2020.Models.DataModels.Person", "UDZ2")
                        .WithMany()
                        .HasForeignKey("PersonId1");

                    b.HasOne("DAIF2020.Models.DataModels.Person", "Supervisor")
                        .WithMany()
                        .HasForeignKey("PersonId2");

                    b.HasOne("DAIF2020.Models.SettingModels.Zone", "Zone1")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.HasOne("DAIF2020.Models.SettingModels.Zone", "Zone2")
                        .WithMany()
                        .HasForeignKey("ZoneId1");
                });

            modelBuilder.Entity("DAIF2020.Planner.Models.DataModels.Activity", b =>
                {
                    b.HasOne("DAIF2020.Models.SettingModels.ActivityStatus", "ActivityStatus")
                        .WithMany()
                        .HasForeignKey("ActivityStatusId");

                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("DAIF2020.Models.DataModels.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("DAIF2020.TSM.Models.DataModels.TSMGame", b =>
                {
                    b.HasOne("DAIF2020.TSM.Models.DataModels.TSMGameStatus", "TSMGameStatus")
                        .WithMany()
                        .HasForeignKey("TSMGameStatusId");
                });

            modelBuilder.Entity("DAIF2020.TheLab.Models.DataModels.PoolGameReceipt", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.PoolGame", "PoolGame")
                        .WithMany()
                        .HasForeignKey("PoolGameId");

                    b.HasOne("DAIF2020.Models.SettingModels.ReceiptCategory", "ReceiptCategory")
                        .WithMany()
                        .HasForeignKey("ReceiptCategoryId");

                    b.HasOne("DAIF2020.Models.SettingModels.ReceiptStatus", "ReceiptStatus")
                        .WithMany()
                        .HasForeignKey("ReceiptStatusId");

                    b.HasOne("DAIF2020.Models.SettingModels.ReceiptType", "ReceiptType")
                        .WithMany()
                        .HasForeignKey("ReceiptTypeId");
                });

            modelBuilder.Entity("DAIF2020.TheLab.Models.DataModels.Receipt", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("DAIF2020.Models.SettingModels.ReceiptCategory", "ReceiptCategory")
                        .WithMany()
                        .HasForeignKey("ReceiptCategoryId");

                    b.HasOne("DAIF2020.Models.SettingModels.ReceiptStatus", "ReceiptStatus")
                        .WithMany()
                        .HasForeignKey("ReceiptStatusId");

                    b.HasOne("DAIF2020.Models.SettingModels.ReceiptType", "ReceiptType")
                        .WithMany()
                        .HasForeignKey("ReceiptTypeId");
                });

            modelBuilder.Entity("DAIF2020.TheLab.Models.DataModels.WeeklyReceipt", b =>
                {
                    b.HasOne("DAIF2020.Models.DataModels.Person", "Referee")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("DAIF2020.Models.SettingModels.ReceiptStatus", "ReceiptStatus")
                        .WithMany()
                        .HasForeignKey("ReceiptStatusId");
                });

            modelBuilder.Entity("DAIF2020.TheLab.Models.DataModels.ZoneGameReceipt", b =>
                {
                    b.HasOne("DAIF2020.Models.SettingModels.ReceiptCategory", "ReceiptCategory")
                        .WithMany()
                        .HasForeignKey("ReceiptCategoryId");

                    b.HasOne("DAIF2020.Models.SettingModels.ReceiptStatus", "ReceiptStatus")
                        .WithMany()
                        .HasForeignKey("ReceiptStatusId");

                    b.HasOne("DAIF2020.Models.SettingModels.ReceiptType", "ReceiptType")
                        .WithMany()
                        .HasForeignKey("ReceiptTypeId");

                    b.HasOne("DAIF2020.Models.DataModels.ZoneGame", "ZoneGame")
                        .WithMany()
                        .HasForeignKey("ZoneGameId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
